services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "9002:8080"
    env_file:
      - .env
    environment:
      - GEMINI_API_KEY
      - DEEPGRAM_API_KEY

  genkit:
    build:
      context: .
      dockerfile: Dockerfile.genkit
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - GEMINI_API_KEY
      - DEEPGRAM_API_KEY
